import Head from "next/head";
import Link from "next/link";
import {useEffect, useState} from "react";
import styles from "../../styles/Home.module.css";
import {instance} from "../../utlis";
import {EpisodeCard} from "../../components";

export default function Episodes(props) {
    const [data, setData] = useState([]);
    const [info, setInfo] = useState();
    const [page, setPage] = useState(1);
    const [searchValue, setSearchValue] = useState("");

    useEffect(() => {
        fetch(`https://rickandmortyapi.com/api/episode/?page=${page}`)
            .then((res) => res.json())
            .then((res) => {
                setData((prev) => [...prev, ...res.results]);
                setInfo(res.info);
            });
    }, [page]);

    useEffect(() => {
        fetch(`https://rickandmortyapi.com/api/episode/?name=${searchValue}`)
            .then((res) => res.json())
            .then((res) => {
                setData(res.results);
                setInfo(res.info);
            });
    }, [searchValue]);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <input placeholder={'Filter by name'}
                value={searchValue}
                onChange={(e) => setSearchValue(e.target.value)}
            />
            <main className={styles.main}>
                {data?.map((episode) => (
                    <Link href={`/episodes/${episode.id}`} key={episode.id}>
                        <EpisodeCard
                            name={episode.name}
                            air_date={episode.air_date}
                            episode={episode.episode}
                        />
                    </Link>
                ))}

                {info?.next && (
                    <button onClick={() => setPage((prev) => ++prev)}>LOAD MORE</button>
                )}
            </main>
        </>
    );
}

export async function getServerSideProps(ctx) {

    // Fetch data from external API
    const data = await instance({
        url: 'episode',
        params: ctx.query,
    });

    // Pass data to the page via props
    return {props: data.data};
}